apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkusdroneshop-reward
  namespace: quarkusdroneshop-cicd
  labels:
    app: quarkusdroneshop-reward
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/quarkusdroneshop/quarkusdroneshop-reward'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-run
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven-no-settings11
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value: "clean package"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: push-oc-apps
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=reward -n quarkusdroneshop-demo || true
            oc delete bc/reward -n quarkusdroneshop-demo || true
            oc new-build --binary --name=reward --image-stream=java:openjdk-17-ubi8 -n quarkusdroneshop-demo
            oc start-build reward --from-dir=target/quarkus-app/ --follow -n quarkusdroneshop-demo
            oc new-app reward --name=reward --allow-missing-images -n quarkusdroneshop-demo
            oc set env deployment/reward JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkusdroneshop-demo

            PGSQL_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.PGSQL_URL}')
            oc set env deployment/reward PGSQL_URL=$PGSQL_URL -n quarkusdroneshop-demo
            PGSQL_USER=$(oc get secret droneshopdb-pguser-droneshopadmin -n quarkusdroneshop-demo -o=jsonpath='{.data.user}' | base64 --decode)
            oc set env deployment/reward PGSQL_USER=$PGSQL_USER -n quarkusdroneshop-demo
            PGSQL_PASS=$(oc get secret droneshopdb-pguser-droneshopadmin -n quarkusdroneshop-demo -o=jsonpath='{.data.password}' | base64 --decode)
            oc set env deployment/reward PGSQL_PASS=$PGSQL_PASS -n quarkusdroneshop-demo
            
            KAFKA_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/reward KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkusdroneshop-demo
            QUARKUS_LOG_LEVEL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.QUARKUS_LOG_LEVEL}')
            oc set env deployment/reward QUARKUS_LOG_LEVEL=$QUARKUS_LOG_LEVEL -n quarkusdroneshop-demo
      workspaces:
        - name: source
          workspace: shared-workspace